[general]
import = [
    "~/.config/alacritty-framework16-light/themes/themes/alabaster.toml"
]

live_config_reload = true

[terminal.shell]
program = "/usr/bin/env"
args = ["zsh", "-l"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 110, lines = 50 }
opacity = 0.93
blur = false
padding = { x = 1, y = 1 }

[font]
normal = { family = "Berkeley Mono", style = "Text" }
bold = { style = "SemiBold" }
size = 12
offset = { x = -1, y = -1 }

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
    { key = "N", mods = "Control | Shift", action = "CreateNewWindow" },
    { key = "N", mods = "Alt | Shift", action = "SpawnNewInstance" },
    { key = "L", mods = "Alt | Shift", action = "ClearHistory" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "+", mods = "Control | Shift", action = "IncreaseFontSize" },
    { key = "=", mods = "Control", action = "ResetFontSize" }
]

[debug]
persistent_logging = true

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

